loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: < S3_BUCKET_NAME >
      ruler: < S3_BUCKET_NAME >
      admin: < S3_BUCKET_NAME >
    type: s3
    s3:
      endpoint: < S3_ENDPOINT >
      region: < S3_REGION >
      secretAccessKey: < S3_SECRET >
      accessKeyId: < S3_ACCESS_KEY >
      s3ForcePathStyle: true
      insecure: false
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false